version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./todo-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
